### ISSUE TITLE
Hi, I get Unit test fail-s

### ISSUE THREAD

**Issue by Infinitusvoid** [mattearly/ArcherEngine#35]
![image](https://user-images.githubusercontent.com/84730862/176671307-ed7b063e-d77b-4a63-913f-85595f2c981e.png)

**Comment by mattearly** [comment]
ruh roh!  Do you have the resources available?  (run DownloadTestResources exe, unpack to root project directory in a folder called 'RunTimeFiles/' ?

**Comment by mattearly** [comment]
no response for days, closing

**Comment by Infinitusvoid** [comment]
Sorry for later replay.
I have been immersed in some problem. 
I did managed to make it work. 

![image](https://user-images.githubusercontent.com/84730862/177057969-961c3368-36dc-4c18-8cb5-fe09f90b2688.png)

![image](https://user-images.githubusercontent.com/84730862/177057987-3411b915-359d-4c96-b439-f35586ca3926.png)
