### ISSUE TITLE
Editor : Should editor when I run it display anything more than empy black window?

### ISSUE THREAD

**Issue by Infinitusvoid** [mattearly/ArcherEngine#36]

**Comment by mattearly** [comment]
currently, it doesn't do much.  Drag a model file into the window, fly around with WASD/spacebar:up/C:down, right click to toggle cursor on/off. That's about all until it gets updated - its basically in a hello world state that loads models on drag in

**Comment by mattearly** [comment]
no response for days, closing

**Comment by Infinitusvoid** [comment]
Sorry for late replay, I was immersed in some problem.

It works! 

![image](https://user-images.githubusercontent.com/84730862/177058113-455f20f1-b4f4-439b-b9dd-17379856b410.png)
